"""add_pricing_rules_to_aimodel

Revision ID: 0e59915c60fe
Revises: 4fe97c017a84
Create Date: 2024-01-25 04:01:33.295000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e59915c60fe'
down_revision = '4fe97c017a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('pricing_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'pricing_rules')
    # ### end Alembic commands ###
