"""Add provider_job_id

Revision ID: 1f626d9b2a2e
Revises: 5a1e06408e74
Create Date: 2025-12-28 17:50:52.427950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f626d9b2a2e'
down_revision: Union[str, None] = '5a1e06408e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('provider_job_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_provider_job_id'), 'jobs', ['provider_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_provider_job_id'), table_name='jobs')
    op.drop_column('jobs', 'provider_job_id')
    # ### end Alembic commands ###
