"""Update ProviderConfig for AI Providers

Revision ID: 5a1e06408e74
Revises: cbb164462f3e
Create Date: 2025-12-27 20:36:54.341035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1e06408e74'
down_revision: Union[str, None] = 'cbb164462f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_configs', sa.Column('provider_id', sa.String(), nullable=False, server_default='legacy'))
    op.add_column('provider_configs', sa.Column('name', sa.String(), nullable=True))
    op.add_column('provider_configs', sa.Column('encrypted_api_key', sa.String(), nullable=False, server_default='legacy_key'))
    op.add_column('provider_configs', sa.Column('status', sa.String(), nullable=False, server_default='not_tested'))
    op.add_column('provider_configs', sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provider_configs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('provider_configs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('provider_configs_provider_name_key', 'provider_configs', type_='unique')
    op.drop_column('provider_configs', 'api_key')
    op.drop_column('provider_configs', 'provider_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_configs', sa.Column('provider_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_configs', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('provider_configs_provider_name_key', 'provider_configs', ['provider_name'])
    op.drop_column('provider_configs', 'updated_at')
    op.drop_column('provider_configs', 'error_message')
    op.drop_column('provider_configs', 'last_tested_at')
    op.drop_column('provider_configs', 'status')
    op.drop_column('provider_configs', 'encrypted_api_key')
    op.drop_column('provider_configs', 'name')
    op.drop_column('provider_configs', 'provider_id')
    # ### end Alembic commands ###
